module.exports = {
  apps: [
    {
      name: "mm-pure",
      cwd: "/home/jerry/hyperliquid-mm-bot-complete",
      script: "src/mm_hl.ts",
      interpreter: "node",
      interpreter_args: "--experimental-loader ts-node/esm --max-old-space-size=384",
      env: {
        NODE_OPTIONS: "--max-old-space-size=384",
        TS_NODE_TRANSPILE_ONLY: "1",
        TS_NODE_IGNORE: "false",
        BOT_MODE: "PURE_MM",
        MM_ONLY_PAIRS: "kPEPE",
        FORCE_MM_PAIRS: "kPEPE",
        DYNAMIC_CONFIG_ENABLED: "false",
        ROTATION_MODE: "manual",
        MANUAL_ACTIVE_PAIRS: "kPEPE",
        kPEPE_LEVERAGE: "5",
        RISK_TOTAL_CAPITAL_USD: "9000",
        TELEMETRY_PORT: "8083",
      },
      max_memory_restart: "350M",
      kill_timeout: 120000,
      listen_timeout: 120000,
      restart_delay: 3000,
      exp_backoff_restart_delay: 3000,
      max_restarts: 10,
      min_uptime: 10000,
      autorestart: true,
    },
    {
      name: "mm-virtual",
      cwd: "/home/jerry/hyperliquid-mm-bot-complete",
      script: "src/mm_hl.ts",
      interpreter: "node",
      interpreter_args: "--experimental-loader ts-node/esm --max-old-space-size=384",
      env: {
        NODE_OPTIONS: "--max-old-space-size=384",
        TS_NODE_TRANSPILE_ONLY: "1",
        TS_NODE_IGNORE: "false",
        BOT_MODE: "PURE_MM",
        BOT_INSTANCE: "virtual",
        MM_ONLY_PAIRS: "VIRTUAL",
        FORCE_MM_PAIRS: "VIRTUAL",
        DYNAMIC_CONFIG_ENABLED: "false",
        ROTATION_MODE: "manual",
        MANUAL_ACTIVE_PAIRS: "VIRTUAL",
        VIRTUAL_LEVERAGE: "5",
        RISK_TOTAL_CAPITAL_USD: "8000",
        TELEMETRY_PORT: "8084",
      },
      max_memory_restart: "350M",
      kill_timeout: 120000,
      listen_timeout: 120000,
      restart_delay: 3000,
      exp_backoff_restart_delay: 3000,
      max_restarts: 10,
      min_uptime: 10000,
      autorestart: true,
    },
    {
      name: "copy-general",
      cwd: "/home/jerry/hyperliquid-mm-bot-complete",
      script: "scripts/general_copytrade.ts",
      interpreter: "npx",
      interpreter_args: "tsx",
      args: "--live",
      env: {
        COPY_CAPITAL_USD: "2000",
        COPY_MAX_PER_PAIR: "500",
        COPY_LEVERAGE: "3",
        COPY_POLL_SEC: "30",
        COPY_MIN_VALUE_USD: "10000",
        COPY_SCALING_MODE: "fixed",
        COPY_BLOCKED_COINS: "PUMP",
        COPY_ALLOWED_COINS: "LIT,xyz:CL,ASTER,APEX",
        // COPY_PRIVATE_KEY: "..."  // Set on server .env or PM2 env
      },
      max_memory_restart: "150M",
      kill_timeout: 10000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: 5000,
      autorestart: true,
    },
    {
      name: "breakout-bot",
      cwd: "/home/jerry/hyperliquid-mm-bot-complete",
      script: "scripts/breakout_bot.ts",
      interpreter: "npx",
      interpreter_args: "tsx",
      args: "--live",
      env: {
        BREAKOUT_TOKENS: "BTC,ETH,SOL,HYPE",
        BREAKOUT_PRIVATE_KEY: "REDACTED_LEAKED_KEY",
        BREAKOUT_TICK_SEC: "15",
        BREAKOUT_DEFAULT_LEVERAGE: "5",
        BREAKOUT_RISK_PCT: "1.0",
        BREAKOUT_MAX_POSITIONS: "3",
        BREAKOUT_TP_R_MULT: "3.0",
        // DISCORD_BREAKOUT_WEBHOOK: "",  // Set on server
      },
      max_memory_restart: "150M",
      kill_timeout: 10000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: 5000,
      autorestart: true,
    }
  ]
}
